### ISSUE TITLE
UD - two Finnish

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-corpora-conversions#1]
There are two Finnish treebanks under Universal Dependencies: UD_Finnish-FTB/fi_ftb-ud-train.conllu and  UD_Finnish/fi-ud-train.conllu. I included both, is that right? Check with pml-tq.

**Comment by dan-zeman** [comment]
That is right. UD_Finnish is from Turku, UD_Finnish-FTB is from Helsinki. The UD data themselves are conversions from two distinct original annotation styles. And the domains of the treebanks are also different.

**Comment by natalink** [comment]
Thanks Dan, I left both.
