### ISSUE TITLE
HamleDT30 - which bundle?

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-corpora-conversions#7]
2f829afe
HamleDT 3.0 contains three trees: original, converted to Praguian style and converted to conllu. Which one should I take for KonText? Most of the treebanks are available in conllu format in the UD (already online). So the choice is between original vs. Praguian style.

**Comment by dan-zeman** [comment]
I vote for the Prague style:
- It is more useful when multiple treebanks share the same style. Easier to remember the style when you think about your query.
- There are users who prefer the Prague style over UD. If HamleDT is available in the Prague style, these users will have their share of the cake.
- Previous users of Kontext (at the ČNK website) are more likely to have some knowledge or previous exposure to the Prague style.

**Comment by dan-zeman** [comment]
That being said, there are a few treebanks in HamleDT that are not available in UD, mostly due to license issues. If we make these available for searching, it would be useful to provide their UD conversion too.

**Comment by natalink** [comment]
Ok, it's reasonable, I'll do it in Prague style. 

But as for the possibility to set aside each feature from Interset independently, this is not so obvious. I have to generate certain number of columns for the vertical file, where each column stands for some attribute (form, lemma, tag etc.). So I have to generate for each word all possible features from Interset, where most of them will be empty. 

This is a current problem for UD as well, as it si not possible  to simply query [Gender="Fem"], but instead a regular expression [ufeat="._Gender=Fem._"] shouldbe used. I would ask UCNK (or maybe even someone from Plzen) how can I handle this problem. Maybe, it will be possible todo this with dynamic attributes.

**Comment by natalink** [comment]
2f829af
