### ISSUE TITLE
processing MWEs for corpus query systems

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-corpora-conversions#8]
There are several corpora in Lindat repository featuring annotation of multi-word units, e.g. PDT or [ACL RD-TEC 2.0](http://hdl.handle.net/11372/LRT-1661). The question is how to represent them in KonText.  Following are some ways how MWEs (terms, NEs, etc.) might be handled:
### CQL: MWEs as structures

  As suggested by the authors of ACL RD (Behrang and Anne-Kathrin), mwes are incapsuled in structure attribute (<term>), example from the vertical file:

```
in      in      IN
<term class="tech" id="18-1-H01-1017" annotatorid="a1">
dialogue        dialogue        NN
systems system  NNS
<g/>
</term>
,       ,       ,
the     the     DT
<term class="other" id="22-1-H01-1017" annotatorid="a1">
DARPA   DARPA   NNP
Communicator    Communicator    NNP
program program NN
</term>
```

So the CQL query [<term class=".*" />](https://lindat.mff.cuni.cz/services/kontext/run.cgi/view?q=aword%2C%3Cterm+class%3D%22.%2A%22+%2F%3E&q=f;fromp=171;corpname=aclrd20_en_a&attrs=word&attr_allpos=kw&ctxattrs=word&structs=term%2Cg&refs=%3Ddoc.id%2C%3Dterm.class%2C%3Dterm.annotatorid) will give all the terms.
### querying MWE with CQP (in ACL RD)

Following, is the citation from Anne Schumann's letter on how to use CQP to find terms
_Terms = /region[term]; for getting all annotations. (Maybe my syntax is a bit faulty here, but in general it works like this.)
Then one can analyse the result using various combinations of:
tabulate Terms match..matchend[0] lemma; (This will print all term occurrences in their lemmatised form. [0] is a pointer to a token position, it can be shifted using integer values such as -1, 1, etc.)_ 
### CQL: MWEs as attributes

Institute for Czech National Corpus (authors of KonText) represents MWEs as attributes, and
there is a special position in a tag specifying if the word in mwe is a head(H) or a dependent (D). There is a special attribute representing mwe lemma, with parts separated by underscore. Representation in the vertical file will look something like this:

```
dialogue        dialogue        NN.**D**   dialogue_systems
systems system  NNS**H**   dialogue_systems
```

This will handle some non-contiguous expressions like '_dialogue (and not only) systems_', but 
not sure about coordination like in the following case. Which will be the mwe lemma?

```
dialogue        dialogue        NN.**D**   dialogue_systems
and          and       CC
expert           expert     NN.**D**  expert_systems
systems system  NNS**H**   ???????????
```
### PML-TQ approach

In Prague Dependency Treebank, you can search for mwes with [Prague Markup Language](https://lindat.mff.cuni.cz/services/pmltq/#!/treebank/pdt30/help)
Following is the[ query](https://lindat.mff.cuni.cz/services/pmltq/#!/treebank/pdt30/query/C4WgTg9hwAQFAG0YFsCmyBGqwoO6oGd4YSSlgBPAB1RgF4YAiAG1QA91VGAaY0-ksAB2EACaoAdGABmRUCPEwkAQwD0rNlOkxlIBbQAkVMADchASxgAuBggC6MO9zgCBwsZJly9HpTvXsWjo+igaiYACuABYU1rYwEGCiMAB8MEamFhKJyXZOLq4ADGww7uJa3vp+5skMBgTAYKiiEjWOjs4k4gQAxqhCospCsPK+9Y3NcQWkKgGaMsFVCDmp6cZm5tlJOgMJ2wA86eHRFFuieY4A3HBAA/result/svg) over PDT provided by Eduard Bejcek which identifies some non-contiguous constructions (it is only in Czech):

```
t-root
[ member mwes
     [ type = "lexeme",
          tnode.rfs t-node [ a/lex.rf a-node $prvni := [] ],
          tnode.rfs t-node [ a/lex.rf a-node $druhy := [ ord > $prvni.ord ]],
       0x tnode.rfs t-node [ id = $stred.id ] ],
  descendant t-node $stred :=
     [ a/lex.rf a-node [ord > $prvni.ord and ord < $druhy.ord]] ];
```

**Comment by languagerecipes** [comment]
The major problem with our tag-based methodology is that we cannot address issues that result from what I would call ellipsis. An example is the case of 

> `... information extraction and retrieval ...`

where the terms are `information extraction`and`information retrieval.` 

The other question is how to treat nested MWEs in which the text spans cross over each other. I do not have an example to give right away but I am sure it is possible to find them. Even if a nested term is within another term, then I am not sure how we can use CQL to extract terms at the outer boundary.

It seems to me that using PDT methodology can address problems mentioned above but it comes at the expense of  requirements for more complex queries.

**Comment by Ansa211** [comment]
This issue has been moved to https://github.com/natalink/mwe_noske/issues/2
