### ISSUE TITLE
NULL in Bengali HamleDT 3.0

### ISSUE THREAD

**Issue by natalink** [ufal/lindat-corpora-conversions#9]
In Bengali treebank ( http://lindat.mff.cuni.cz/services/kontext/run.cgi/first?shuffle=1&reload=&corpname=hamledt_30_bn_a&queryselector=cqlrow&iquery=&lemma=&phrase=&word=&char=&cql=[pos%3D%22.*%22]&default_attr=word&fc_lemword_window_type=both&fc_lemword_wsize=5&fc_lemword=&fc_lemword_type=all&sca_s.id=  ), there are some strange NULLs:

তাঁদের চাপে গাড়ীর মালিকরা দূষণ প্রতিরোধ করতে ব্যবস্থা দরকার NULL সেগুলি কাজে লাগাতে বাধ্য হল
মদনার অনুরোধ NULL তাকে এ-বাড়ির সিঁড়ির কোণে একটু থাকতে অনুমতি
যুদ্ধই NULL ইউরোপের নিয়তি
ঘরবাড়ি NULL আসবাবপত্র রং করতে ব্যবহার করা রকম যৌগ

I asked Rajdeep about it, he says that there should be some words (presumably some kind of articles or connectors instead, but he is not sure). @dan-zeman  shall I leave it as it is?

**Comment by dan-zeman** [comment]
These are empty nodes representing elided words. You can safely omit them from the surface representation but be warned that they have dependents, so you have to be careful about the parent-related attributes of the dependents.

NB: Bengali and Telugu is not too interesting in its current form. Even after removing the NULL nodes you will not get fluent text. The nodes in the treebank represent chunks of original text. There were other words in the chunk but they are not visible in the treebank.

**Comment by natalink** [comment]
Well, as the corpus is buggy anyway, I will leave NULLs as they are. Just as a warning that something must be there. Thanks.
